# Site settings
author: Julianna Tetreault
title: Julianna Codes
header-img: img/home-bg.png
email: juliannatetreault@icloud.com
copyright_name: Julianna Tetreault
description: > # this means to ignore newlines until "baseurl:"
  Let's talk code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  juliannatetreault

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
